name: flutter_simple_shopify
description: A new Flutter package which provides help in creating a mobile app of a shopify store.
version: 0.0.26-alpha
homepage: https://github.com/ThinkSimple/flutter_simple_shopify

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.0.0
  freezed_annotation: ^0.14.1
  json_serializable: ^4.1.1
  shared_preferences: ^2.0.6
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  freezed: ^0.14.1+3
  injectable_generator: ^1.3.0
  pedantic: ^1.11.0
